### ISSUE TITLE
Plugin not implement when run "proxy" with --filter JWT:jwt.so:jwt.json

### ISSUE THREAD

**Issue by zloss** [fagongzi/gateway#84]
when I run "./proxy --addr=0.0.0.0:80 --addr-rpc=0.0.0.0:9091 \
--filter JWT:jwt.so:jwt.json \
--addr-store=etcd://127.0.0.1:2379 --namespace=product"
I got an error  like " plugin not implemented".
After googling the issue,  I found that "https://github.com/golang/go/issues/19569"
plugin: requires CGO_ENABLED=1
but in the release.sh  , CGO_ENABLED was set to 0 by default.

**Comment by zhangxu19830126** [comment]
If you want to use custom filter, you need to build gateway by your self. Because:

**Comment by zhangxu19830126** [comment]
If you want to use custom filter, you need to build gateway by your self. Because:

1. when build a go using cgo,  you can found that the binary depends on gcc and some .so files if you using ldd to check, it was unfriendly to containerization.
2. you must be sure the env of gateway compile,  plugin compile and the docker images are same.
3. the release.sh is used for build docker images.

**Comment by zloss** [comment]
Thanks fr reply. Maybe I sould pack the JWT plugin as an internal filter , then I can build the proxy without CGO.
